language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
script:
  - yarn build
  - yarn test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
